// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/GridListGameSetItem.vue')['default']
    GridList: typeof import('./src/components/GridList.vue')['default']
    GridListGameSetItem: typeof import('./src/components/GridListGameSetItem.vue')['default']
    GridListItem: typeof import('./src/components/GridListPersonItem.vue')['default']
    GridListPersonItem: typeof import('./src/components/GridListPersonItem.vue')['default']
    MainLayout: typeof import('./src/layouts/mainLayout.vue')['default']
    PrimaryButton: typeof import('./src/components/PrimaryButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondaryButton: typeof import('./src/components/SecondaryButton.vue')['default']
  }
}
