receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:5555

exporters:
  logging:
    loglevel: debug
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
  prometheus:
    endpoint: '0.0.0.0:8765'
    namespace: test-space
    const_labels:
      app: lasertag
    send_timestamps: true
    metric_expiration: 10m
    resource_to_telemetry_conversion:
      enabled: true

processors:
  batch:

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging,prometheus]
    traces:
      receivers: [otlp]
      exporters: [logging, otlp]