receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:5555

exporters:
  logging:
    loglevel: debug
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
  prometheus:
    endpoint: '0.0.0.0:8765'
    namespace: test-space
    const_labels:
      app: lasertag
    send_timestamps: true
    metric_expiration: 10m
    resource_to_telemetry_conversion:
      enabled: true
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
    tenant_id: "tenant1"
    labels:
      attributes:
        container_name: "localhost"
        container_id: "myid"

processors:
  batch:
  # Data sources: traces
  probabilistic_sampler:
    hash_seed: 22
    sampling_percentage: 80

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging,prometheus]
    traces:
      receivers: [otlp]
      exporters: [logging, otlp]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, loki]